<?
define("PURCHASE_ORDER_LIST", 10);
define("USE_EXPOSURE_LIST", 11);
define("SERIES_LIST", 12);
define("FOUNDATION_SYSTEM_LIST", 13);
define("WALL_TYPE_LIST", 14);
define("ACCESSORIES_TYPE_LIST", 15);
define("PROVINCES_HIGHLOAD", 3);
define("CITIES_HIGHLOAD", 4);
define("MODEL_HIGHLOAD", 1);
define("ACCESSORIES_HIGHLOAD", 2);
define("LOADING_TABLE_HIGHLOAD", 6);
define("USE_EXPOSURE_LIST_HIGHLOAD", 11);
define("GAUGE_VARIANTS_HIGHLOAD", 16);
define("MODEL_LIVE_LOAD_HIGHLOAD", 7);
define("RETAILED_PRICE_HIGHLOAD", 8);
define("CONSTANTS_HIGHLOAD", 9);
define("SHIPPING_WEIGHT_HIGHLOAD", 18);
define("WEIGHT_MEASURES_HIGHLOAD", 19);
define("WEIGHT_HIGHLOAD", 17);
define("FREIGHT_COST_HIGHLOAD", 5);
define("QUOTATION_SYSTEM_HIGHLOAD", 20);
define("EMAILS_SOURCES_HIGHLOAD", 22);
define("ENDWALL_EXTENSION_HIGHLOAD", 23);

define("OPEN_WALL_TYPE", 1);
define("SOLID_WALL_TYPE", 2);
define("MINI_SERIE", 5);
define("Q_SERIE", 1);
define("S_SERIE", 2);

define("FOUNDATION_SYSTEM_THROUGH", 1);
define("FOUNDATION_SYSTEM_INDUSTRIAL_BASEPLATES", 2);
define("FOUNDATION_SYSTEM_CHANNEL", 3);
define("FOUNDATION_SYSTEM_MONOLITHIC_POUR", 4);

define("ON_PROVINCE", 5);

//Constants
define("ARCH_RETAIL_PRICE_FOR_CHANNEL", 1);
define("ARCH_RETAIL_PRICE_FOR_MINI_CHANNEL", 2);
define("ARCH_RETAIL_PRICE_FOR_INDUSTRIAL", 3);
define("ENDWALL_RETAIL_PRICE_FOR_CHANNEL", 4);
define("ENDWALL_RETAIL_PRICE_FOR_MINI_CHANNEL", 5);
define("ENDWALL_RETAIL_PRICE_FOR_INDUSTRIAL", 6);
define("DRAWINGS", 7);
define("ENDWALL_FREIGHT", 8);
define("BASEPLATE_FREIGHT", 9);
define("CA_VARIABLE_1", 10);
define("CA_VARIABLE_2", 11);
define("US_VARIABLE_1", 12);
define("US_VARIABLE_2", 13);

//Lead
define("STYLE_FIELD", "UF_CRM_F27C976E");
define("WIDTH_FIELD", "UF_CRM_4DDB6A2B");
define("LENGTH_FIELD", "UF_CRM_6D19B84");
define("HEIGHT_FIELD", "UF_CRM_F2E1E039");
define("PROJECT_DETAILS_FIELD", "UF_CRM_A34000ED");
define("MODEL_FIELD", "UF_CRM_16545DDD");
define("LEAD_NUMBER_FIELD", "UF_CRM_6AC1ECC9");
define("STATE_FIELD", "UF_CRM_1620224095");
define("STATE_FIELD_ID", "601");
define("PROVINCE_FIELD", "UF_CRM_1607507237");
define("PROVINCE_FIELD_ID", "174");

//Sources 
define("BRAEMAR_SOURCE_ID", "225A5CAD");
define("PIONEER_SOURCE_ID", "B9448ECE");

//Emails addresses
define("BRAEMAR_EMAIL_ADRESS", "1");
define("PIONEER_EMAIL_ADRESS", "2");

//Users id
define("DEBBIE_SIN", "24");
define("MELVYN_HO", "72");
define("LOURDES_MARC", "67");
define("KRYSTAL_WILLIAMS", "71");
define("ABBE_SIN", "59");

//Projects id
define("OPERATIONS", "14");

//Mailbox id
define("ADMIN_MAILBOX_ID", "1");

define("EXTERNAL_CALL_TYPE", "1");